version: '2.3'

services:
  conda:
    image: "diegoferigo/conda:10.1"
    container_name: "conda"
    command: "bash"
    init: true
    #environment:
    #  - MAMBA_ROOT_PREFIX="~/.micromamba"
    #  - YARP_NAME_SPACE=/dferigo
    #ports:
    #  - 8000:8000
    #  - 8888:8888
    working_dir: "$HOME"
    stdin_open: true
    tty: true
    network_mode: "host"
    security_opt:
      - apparmor:unconfined
    dns:
      - 8.8.8.8

devenv:
  version: '1.0'
  conda:
    user: "dferigo"
    project_dir: "$HOME/git"
    resources:
      directories:
        - "$HOME/.dockerdot/ccache:$HOME/.ccache"
        - "$HOME/.dockerdot/ignition:$HOME/.ignition"
        - "$HOME/.dockerdot/config/qtcreator:$HOME/.config/QtProject"
        - "$HOME/.dockerdot/config/JetBrains:$HOME/.config/JetBrains"
        - "$HOME/.dockerdot/local/share/JetBrains:$HOME/.local/share/JetBrains"
        - "$HOME/.dockerdot/cache:$HOME/.cache"
        - "$HOME/.dockerdot/local/share/z:$HOME/.local/share/z"
        #- "$HOME/.dockerdot/julia:$HOME/.julia"
        #- "$HOME/.dockerdot/micromamba:$HOME/.micromamba"
      files:
        - "$HOME/.dockerdot/z:$HOME/.z"
        - "$HOME/.dockerdot/bash_history:$HOME/.bash_history"
        - "$HOME/.dockerdot/local/share/fish/fish_history:$HOME/.local/share/fish/fish_history"
    gpu: "nvidia"
    x11: "xauth"
    #matlab:
    #  folder: "/opt/MATLAB/R2020a"
    #  #mac: "wlp2s0"
    #  dotdir: "$HOME/.dockerdot/matlab:$HOME/.matlab:rw"
    gdb: true
    git:
      username: "Diego Ferigo"
      email: "diego.ferigo@iit.it"
