version: '2.3'

services:
  rl:
    image: "diegoferigo/rl:latest"
    container_name: "rl"
    command: "bash"
    init: true
    environment:
      - YARP_NAME_SPACE=/dferigo
    ports:
      - 8000:8000
      - 8888:8888
    working_dir: "$HOME"
    stdin_open: true
    tty: true
    network_mode: "host"
    security_opt:
      - apparmor:unconfined
    dns:
      - 8.8.8.8

devenv:
  version: '1.0'
  rl:
    user: "dferigo"
    project_dir: "$HOME/git"
    resources:
      directories:
        - "$HOME/.dockerdot/ccache:$HOME/.ccache"
        - "$HOME/.dockerdot/ignition:$HOME/.ignition"
        - "$HOME/.dockerdot/config/qtcreator:$HOME/.config/QtProject"
        - "$HOME/.dockerdot/config/JetBrains:$HOME/.config/JetBrains"
        - "$HOME/.dockerdot/local/share/JetBrains:$HOME/.local/share/JetBrains"
        - "$HOME/.dockerdot/cache:$HOME/.cache"
      files:
        - "$HOME/.dockerdot/z:$HOME/.z"
        - "$HOME/.dockerdot/bash_history:$HOME/.bash_history"
    gpu: "intel"
    x11: "xauth"
    # matlab:
    #   folder: "/opt/MATLAB/R2018a"
    #   # mac: "wlp2s0"
    #   dotdir: "$HOME/.dockerdot/matlab:$HOME/.matlab:rw"
    gdb: true
    git:
      username: "Diego Ferigo"
      email: "diego.ferigo@iit.it"
