version: '2.3'

services:
  tools:
    image: "diegoferigo/tools"
    container_name: "tools"
    command: "bash"
    init: true
    ports:
      - 8000:8000
      - 8888:8888
    stdin_open: true
    tty: true
    dns:
      - 8.8.8.8

devenv:
  version: '1.0'
  tools:
    user: "dferigo"
    gpu: "intel"
    x11: "xauth"
    matlab:
      folder: "/usr/local/MATLAB/R2018a"
      mac: "wlp2s0"
      dotdir: "$HOME/.dockerdot/matlab:$HOME/.matlab"
    #init: "systemd"
    #gdb: true
    git:
      username: "Diego Ferigo"
      email: "diego.ferigo@iit.it"
      ##gpg:
      ##  - key: XXXX
