version: '3.0'

services:

  conda_cuda11.2:
    build:
      args:
        from: ubuntu:focal
        cudatoolkit_version: "11.2.*"
      context: .
      dockerfile: Dockerfile
    image: diegoferigo/conda:11.2
  
  conda_cuda10.1:
    build:
      args:
        from: diegoferigo/cuda:10.1-cudnn7-devel-ubuntu20.04
      context: .
      dockerfile: Dockerfile
    image: diegoferigo/conda:10.1
