version: '2'

services:
  #
  # MASTER CONTAINERS
  #
  ros-master:
    image: "${ROS_MASTER_IMAGE}"
    container_name: ros-master
    ports:
      - ${ROS_MASTER_PORT}:${ROS_MASTER_PORT}
    command: roscore

  #yarp-server:
    #image: "${YARP_MASTER_IMAGE}"
    #container_name: yarp-server
    #environment:
      #- "YARP_NAME_SPACE=${YARP_NAME_SPACE}"
      #- "USERNAME=${USERNAME}"
    #ports:
      #- "${YARP_MASTER_PORT}:${YARP_MASTER_PORT}"
      #- "${YARP_MASTER_PORT}:${YARP_MASTER_PORT}/udp"
    #command: sh -c 'yarp namespace ${YARP_NAME_SPACE} && yarpserver'

  #
  # DEVELOPMENT CONTAINERS
  #
  development:
    image: "${DEVELOPMENT_IMAGE}"
    container_name: development
    environment:
      # ROS/YARP Variables
      #- "ROS_HOSTNAME=development"
      #- "ROS_MASTER_URI=http://ros-master:${ROS_MASTER_PORT}"
      - "YARP_NAME_SPACE=${YARP_NAME_SPACE}"
      # Runtime user variables
      - "USER_UID=${USER_UID}"
      - "USER_GID=${USER_GID}"
      - "USERNAME=${USERNAME}"
      # X11 Forwarding
      - "XAUTHORITY=${XAUTH}"
      - "DISPLAY"
      # Misc variables
      - "COPY_ATOM_PACKAGES=1"
      - "PROJECT_DIR=${PROJECT_DIR}"
      # Git variables
      - "GIT_USER_NAME=${GIT_USER_NAME}"
      - "GIT_USER_EMAIL=${GIT_USER_EMAIL}"
      # GPG commit signing variables
      # TODO: the only workaround I found to sign a commit is executing with:
      #         $ script -q -c "GPG_TTY=/dev/pts/0 git commit -m (...)
      #       since $(tty) is not recognized either with docker exec and inside script
      # - "GIT_USE_GPG=1"
      # - "GIT_GPG_KEY=${GIT_GPG_KEY}"
    # depends_on:
      # - ros-master
      # - yarp-server
    volumes:
      # X11 Forwarding
      - "${XSOCK}:${XSOCK}:rw"
      - "${XAUTH}:${XAUTH}:rw"
      # Persistent folders
      - "/home/${USERNAME}/.gnupg:/home/${USERNAME}/.gnupg:rw"
      - "${PROJECT_DIR}:/home/${USERNAME}/${PROJECT_BASENAME}:rw"
      - "/dev/shm:/dev/shm:rw"
      - ${HOST_ATOM_DOT_DIR}:/home/${USERNAME}/.atom:rw
      - ${HOST_ATOM_CONF_DIR}:/home/${USERNAME}/.config/Atom:rw
      - ${HOST_GITKRAKEN_DOT_DIR}:/home/${USERNAME}/.gitkraken:rw
      - ${HOST_YARPLOCAL_DIR}:/home/${USERNAME}/.local/share/yarp:rw
      - ${HOST_CCACHE_DIR}:/home/${USERNAME}/.ccache:rw
      - ${HOST_MATLAB_DIR}:/home/${USERNAME}/.MATLAB:rw
      - ${HOST_MATLAB_DOT_DIR}:/home/${USERNAME}/.matlab:rw
      - ${HOST_BASH_HISTORY_FILE}:/home/${USERNAME}/.bash_history:rw
      # GPG commit signing
      # - "/dev/console:/dev/console:rw"
    devices:
      # HW Acceleration for intel cards
      - "/dev/dri:/dev/dri"
    ports:
      - "11000-11${YARP_NUM_PORTS}:10000-10${YARP_NUM_PORTS}"
      - "11000-11${YARP_NUM_PORTS}:10000-10${YARP_NUM_PORTS}/udp"
    mac_address: ${HOST_MATLAB_MAC}
    # -i
    stdin_open: true
    # -t
    tty: true
    # Enable ptrace for running GDB
    # https://github.com/moby/moby/issues/7276
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: su -c 'atom -f' ${USERNAME}

  gitkraken:
    image: "${GITKRAKEN_IMAGE}"
    container_name: gitkraken
    environment:
      - "USER_UID=${USER_UID}"
      - "USER_GID=${USER_GID}"
      - "USERNAME=${USERNAME}"
      - "XAUTHORITY=${XAUTH}"
      - "PROJECT_DIR=${PROJECT_DIR}"
      - "DISPLAY"
    volumes:
      - "${XSOCK}:${XSOCK}:rw"
      - "${XAUTH}:${XAUTH}:rw"
      - "${HOST_GITKRAKEN_CONF_DIR}:/home/${USERNAME}/.gitkraken:rw"
      - "${PROJECT_DIR}:/home/${USERNAME}/${PROJECT_BASENAME}:rw"
      - "/dev/shm:/dev/shm:rw"
      # Waiting gitkraken GPG signing support
      # - "/home/${USERNAME}/.gnupg:/home/${USERNAME}/.gnupg:rw"
    devices:
      # HW Acceleration for intel cards
      - "/dev/dri:/dev/dri"
    # -i
    stdin_open: true
    # -t
    tty: true
    command: su -c "gitkraken" ${USERNAME}
