version: '2'

services:
  #
  # MASTER CONTAINERS
  #
  ros-master:
    image: "${ROS_MASTER_IMAGE}"
    container_name: ros-master
    ports:
      - ${ROS_MASTER_PORT}:${ROS_MASTER_PORT}
    command: roscore

  # yarp-master:
  #   image: "${YARP_MASTER_IMAGE}"
  #   container_name: yarp-master
  #   ports:
  #     - ${YARP_MASTER_PORT}:${YARP_MASTER_PORT}
  #   command:

  #
  # DEVELOPMENT CONTAINERS
  #
  development:
    image: "${DEVELOPMENT_IMAGE}"
    container_name: development
    environment:
      - "ROS_HOSTNAME=development"
      - "ROS_MASTER_URI=http://ros-master:${ROS_MASTER_PORT}"
      - "USER_UID=${USER_UID}"
      - "USER_GID=${USER_GID}"
      - "USERNAME=${USERNAME}"
      - "XAUTHORITY=${XAUTH}"
      - "COPY_ATOM_PACKAGES=1"
      - "PROJECT_DIR=${PROJECT_DIR}"
      - "GIT_USER_NAME=${GIT_USER_NAME}"
      - "GIT_USER_EMAIL=${GIT_USER_EMAIL}"
      - "DISPLAY"
    depends_on:
      - ros-master
    volumes:
      - "${XSOCK}:${XSOCK}:rw"
      - "${XAUTH}:${XAUTH}:rw"
      - "${ATOM_CONF}:/home/${USERNAME}/.atom:rw"
      - "${PROJECT_DIR}:/home/${USERNAME}/${PROJECT_BASENAME}:rw"
      - "/home/${USERNAME}/.bash_history_docker:/home/${USERNAME}/.bash_history:rw"
    command: su -c "atom -f" ${USERNAME}

  gitkraken:
    image: "${DEVELOPMENT_IMAGE}"
    container_name: gitkraken
    environment:
      - "USER_UID=${USER_UID}"
      - "USER_GID=${USER_GID}"
      - "USERNAME=${USERNAME}"
      - "XAUTHORITY=${XAUTH}"
      - "PROJECT_DIR=${PROJECT_DIR}"
      - "DISPLAY"
    volumes:
      - "${XSOCK}:${XSOCK}:rw"
      - "${XAUTH}:${XAUTH}:rw"
      - "${GITKRAKEN_CONF}:/home/${USERNAME}/.gitkraken:rw"
      - "${PROJECT_DIR}:/home/${USERNAME}/${PROJECT_BASENAME}:rw"
    command: su -c "gitkraken" ${USERNAME}
