version: '2'

services:
  #
  # MASTER CONTAINERS
  #
  ros-master:
    image: "${ROS_MASTER_IMAGE}"
    container_name: ros-master
    ports:
      - ${ROS_MASTER_PORT}:${ROS_MASTER_PORT}
    command: roscore

  yarp-server:
    image: "${YARP_MASTER_IMAGE}"
    container_name: yarp-server
    environment:
      - "YARP_NAME_SPACE=${YARP_NAME_SPACE}"
      - "USERNAME=${USERNAME}"
    ports:
      - "${YARP_MASTER_PORT}:${YARP_MASTER_PORT}"
      - "${YARP_MASTER_PORT}:${YARP_MASTER_PORT}/udp"
    command: sh -c 'yarp namespace ${YARP_NAME_SPACE} && yarpserver'

  #
  # DEVELOPMENT CONTAINERS
  #
  development:
    image: "${DEVELOPMENT_IMAGE}"
    container_name: development
    environment:
      #- "ROS_HOSTNAME=development"
      #- "ROS_MASTER_URI=http://ros-master:${ROS_MASTER_PORT}"
      - "YARP_NAME_SPACE=${YARP_NAME_SPACE}"
      - "USER_UID=${USER_UID}"
      - "USER_GID=${USER_GID}"
      - "USERNAME=${USERNAME}"
      - "XAUTHORITY=${XAUTH}"
      - "COPY_ATOM_PACKAGES=1"
      - "PROJECT_DIR=${PROJECT_DIR}"
      - "GIT_USER_NAME=${GIT_USER_NAME}"
      - "GIT_USER_EMAIL=${GIT_USER_EMAIL}"
      - "DISPLAY"
    depends_on:
      # - ros-master
      - yarp-server
    volumes:
      - "${XSOCK}:${XSOCK}:rw"
      - "${XAUTH}:${XAUTH}:rw"
      - "${ATOM_CONF}:/home/${USERNAME}/.atom:rw"
      - "${PROJECT_DIR}:/home/${USERNAME}/${PROJECT_BASENAME}:rw"
      - "/home/${USERNAME}/.bash_history_docker:/home/${USERNAME}/.bash_history:rw"
    ports:
      - "11000-11${YARP_NUM_PORTS}:10000-10${YARP_NUM_PORTS}"
      - "11000-11${YARP_NUM_PORTS}:10000-10${YARP_NUM_PORTS}/udp"
    command: su -c 'atom -f' ${USERNAME}

  gitkraken:
    image: "${DEVELOPMENT_IMAGE}"
    container_name: gitkraken
    environment:
      - "USER_UID=${USER_UID}"
      - "USER_GID=${USER_GID}"
      - "USERNAME=${USERNAME}"
      - "XAUTHORITY=${XAUTH}"
      - "PROJECT_DIR=${PROJECT_DIR}"
      - "DISPLAY"
    volumes:
      - "${XSOCK}:${XSOCK}:rw"
      - "${XAUTH}:${XAUTH}:rw"
      - "${GITKRAKEN_CONF}:/home/${USERNAME}/.gitkraken:rw"
      - "${PROJECT_DIR}:/home/${USERNAME}/${PROJECT_BASENAME}:rw"
    command: su -c "gitkraken" ${USERNAME}
