name: 'Docker Images'

on:
  push:
  pull_request:
  schedule:
    # Execute a weekly build on Monday at 2AM UTC
    - cron:  '0 2 * * 1'

jobs:
  # =====
  # TOOLS
  # =====

  tools:
    name: Tools
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: 'Build tools:latest'
        run: make tools

      - name: Login
        if: |
          github.repository == 'diegoferigo/development-iit' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

      - name: Push
        if: |
          github.repository == 'diegoferigo/development-iit' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master'
        run: "docker push diegoferigo/tools:latest"

  # ===========
  # DEVELOPMENT
  # ===========

  development:
    name: Development
    runs-on: ubuntu-18.04
    needs: tools
    strategy:
      matrix:
        target:
          - master
          # - devel

    steps:
      - uses: actions/checkout@master

      - name: 'Build [development@${{ matrix.target }}]'
        run: make development-${{ matrix.target }}

      - name: Login
        if: |
          github.repository == 'diegoferigo/development-iit' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}


      - name: 'Push [development:${{ matrix.target }}]'
        if: |
          github.repository == 'diegoferigo/development-iit' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master'
        run: "docker push diegoferigo/development:${{ matrix.target }}"

      - name: 'Tag [development:latest]'
        if: |
          github.repository == 'diegoferigo/development-iit' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master' &&
          matrix.target == 'master'
        run: "docker tag diegoferigo/development:${{ matrix.target }} diegoferigo/development:latest"

      - name: 'Push [development:latest]'
        if: |
          github.repository == 'diegoferigo/development-iit' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master' &&
          matrix.target == 'master'
        run: "docker push diegoferigo/development:${{ matrix.target }}"

  # ======================
  # REINFORCEMENT LEARNING
  # ======================

  rl:
    name: RL
    runs-on: ubuntu-18.04
    needs: development
    strategy:
      matrix:
        target:
          - master
          - ubuntu

    steps:
      - uses: actions/checkout@master

      - name: 'Build [rl:${{ matrix.target }}]'
        run: make rl-${{ matrix.target }}

      - name: Login
        if: |
          github.repository == 'diegoferigo/development-iit' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

      - name: 'Push [rl:${{ matrix.target }}]'
        if: |
          github.repository == 'diegoferigo/development-iit' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master'
        run: "docker push rl/development:${{ matrix.target }}"

      - name: 'Tag [rl:latest]'
        if: |
          github.repository == 'diegoferigo/development-iit' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master' &&
          matrix.target == 'master'
        run: "docker tag diegoferigo/rl:${{ matrix.target }} diegoferigo/rl:latest"

      - name: 'Push [rl:latest]'
        if: |
          github.repository == 'diegoferigo/development-iit' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master' &&
          matrix.target == 'master'
        run: "docker push diegoferigo/rl:${{ matrix.target }}"
